export default {
  splashIcon: require('./images/splash_icon.png'),
  bootSplashImage: require('./images/app_icon.svg'),
  // TODO: Add app images.
  logo: require('./images/logo.svg'),
  landingBg: require('./images/landing_bg.png'),
  signupBg: require('./images/signup_bg.png'),
  notificationIcon: require('./images/notification_bell.png'),
  oddFrame: require('./images/odd_frame.png'),
  evenFrame: require('./images/even_frame.png'),
  leftArrow: require('./images/left_arrow.png'),
  rightArrow: require('./images/right_arrow.png'),
  chevronRight: require('./images/settings_right_arrow.png'),
  bgOddFrame: require('./images/bg_odd_frame.png'),
  bgEvenFrame: require('./images/bg_even_frame.png'),
  banner1: require('./images/banner_1.png'),
  searchIcon: require('./images/search_icon.png'),
  systemSmallLight: require('./images/SystemSmallLight.png'),
  outlinedFavIcon: require('./images/outlined_fav_icon.svg'),
  outlinedHomeIcon: require('./images/outlined_home_icon.svg'),
  outlinedSettingsIcon: require('./images/outlined_settings_icon.svg'),
  outlinedSearchIcon: require('./images/outlined_search_icon.svg'),
  filledSettingsIconPng: require('./images/filled_settings_icon.png'),
  filledHomeIconPng: require('./images/filled_home_icon.png'),
  appIcon: require('./images/app_icon.svg'),
};
